name: CI
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  arangomigo:
    name: arangomigo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with: { go-version: '1.16' }
      - name: Checkout code
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: Download dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with: { version: lastest }
        continue-on-error: true

      - name: Test
        run: |
          docker run -p 1234:8529 -e ARANGO_ROOT_PASSWORD=simple arangodb/arangodb:3.7.2.1 -d
          sleep 10
          go test ./...
        shell: bash
