name: CI
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  arangomigo:
    name: arangomigo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with: { version: lastest }
        continue-on-error: true

      - name: Test
        run: ./test.sh
        shell: bash
